version: '3.8'

services:
  php:
    image: uyibis/phalcon-app:v5.0.4  # Incrementing version number
    build:
      context: ./docker/php
    volumes:
      - ./app:/var/www/app
      - ./public:/var/www/public
    ports:
      - "${PHP_PORT:-9000}:9000"
    networks:
      - phalcon-network
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/public
    ports:
      - "${PORT:-80}:80"  # Using PORT env variable with default 80
    networks:
      - phalcon-network
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: boardman_app
      MYSQL_USER: phalcon
      MYSQL_PASSWORD: secret
    volumes:
      - ./boardman_app.sql:/docker-entrypoint-initdb.d/boardman_app.sql
      - mysql_data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    networks:
      - phalcon-network

volumes:
  mysql_data:

networks:
  phalcon-network:
    driver: bridge